
name: My Pipeline

on: [push]  # הפעלת הפייפליין בכל פוש

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ping Google
        run: ping -c 4 google.com

 
