name: My First Action

on: push  # Runs when code is pushed

jobs:
  my-job: task 1#Here you put the name of the job
    runs-on: ubuntu-latest # The CI-CD pipeline will run on Ubuntu

steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: שליחת פינג לגוגל
    run: ping -c 4 google.com
